import { Inter } from "next/font/google";

import 'bootstrap/dist/css/bootstrap.min.css';
import 'tachyons';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Detect Face in Image ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="modal-root" ></div> 
        {children}
      </body>
    </html>
  );
}
